### ISSUE TITLE
Loading an MP3 song hangs on "loading" screen

### ISSUE THREAD

**Issue by terminatorbs** [Ikeiwa/EditSaber#18]
When making a new song and selecting an MP3 file, the program just hangs on "loading".  Converting the song to OGG fixes the issue. (same file name, same song, just different format)

**Comment by mashirochan** [comment]
It says multiple times that the only supported song format right now is .ogg..

**Comment by worc** [comment]
it also hangs when loading an OGG file converted from mp3
