### ISSUE TITLE
Clicking ticked checkboxes in Tab menu will tick the next box

### ISSUE THREAD

**Issue by TheGrammarJew** [Ikeiwa/EditSaber#20]
![Example of ticks moving to next box](https://user-images.githubusercontent.com/8527287/41434933-f4281866-6fe2-11e8-9812-9da322230d6f.png)

A very minor bug, but clicking a ticked box in the tab menu will tick the next box in a top-to-bottom sequence. If the bottom box is ticked and clicked, the top box will be ticked.

**Comment by Ikeiwa** [comment]
It's not a bug, I done this to prevent the user having none selected options. Maybe I should lock the uncheck ?
