### ISSUE TITLE
Editor Does Not Launch: DirectX Runtime Needed

### ISSUE THREAD

**Issue by jw15851** [Ikeiwa/EditSaber#24]
I'm using a laptop that has both Intel and NVIDIA graphics.  Application will not launch.  I did configure the graphics to launch the app using NVIDIA, and I switched all graphics over to NVIDIA, yet I still get the error message.  

Graphic drivers are updated, OS is fully updated Windows 10 Pro.

**Comment by theamazingfedex** [comment]
I am experiencing the same issue, with essentially the exact same hardware setup.

**Comment by theamazingfedex** [comment]
I reached out to Ikeiwa, and was told to try installing the [UnrealEngine4 Prereq Setup](https://mega.nz/#!W0hmAaSD!KFSH1aDzPj2l7rlq2goMv8DJEWS19pMpJL1leMcr6nk) to ensure the correct version of DirectX is installed, however I have been unable to test this, as I currently don't have admin rights to my laptop (soon though).

**Comment by rbneville** [comment]
Had the same problem. Fixed it by copying xinput1_3.dll from another program to the editors directory.

**Comment by theamazingfedex** [comment]
Installing the UE4_Prereq_setup as mentioned in my above comment resolved the issues on my laptop.
