### ISSUE TITLE
Install Folder?

### ISSUE THREAD

**Issue by georgehiroshi** [Ikeiwa/EditSaber#28]
I'm wondering, can you use the edit saber, without actually owning the game. I'd just like to try out the editor, but whenever it starts, it just says,
"Please enter your BeatSaber install folder"
I think it's the file I'm supposed to transfer the finished songs to, but I just wanted to try posting on Beat Saver.
Any ideas on what the start screen is about here?

**Comment by megalon** [comment]
The directory can be anywhere on your PC.
It's just asking for the install directory of Beat Saber for convenience.

Please have someone playtest your track several times before submitting it.
You can really only know if a map is good by playing it.

**Comment by georgehiroshi** [comment]
Got it. But it's not like bringing up the finder window like any other save-to-file system. I need to type something. Is it a url thing or just a file name or what?

**Comment by caffeine239** [comment]
try with just manually making it with empty folders.

C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\CustomSongs\

**Comment by georgehiroshi** [comment]
I did it! Thanks!
