### ISSUE TITLE
Incorrect cursor snapping to grid

### ISSUE THREAD

**Issue by dudedan7** [Ikeiwa/EditSaber#6]
Occasionally when pressing the play button to stop the song and reset to the last cursor point, I notice the cursor moves slightly off position from the grid points it should be allowed to snap to depending on the cursor precision setting. Any scrolling with the mouse wheel past that point will keep the incorrect cursor offset and cause further notes to be placed at an incorrect position unless the cursor is reverted all the way back to the beginning of the song. Not sure if there is a guaranteed way to reproduce this but I had:
-Cursor precision set to 1/2
-Played and reset song using the play button

Here is an example of what the scroll position looks like after it moves off position from the grid it should be confined too
![r1xgwcc](https://user-images.githubusercontent.com/31659204/39962775-f5167ea0-5626-11e8-8d4f-3213babef392.png)

**Comment by dudedan7** [comment]
After further use it appears this spacing issue can even be activated by something as simple as scrolling too fast in one particular direction.

**Comment by Ikeiwa** [comment]
umh what version are you using ?

**Comment by Ikeiwa** [comment]
it's weird, I can't replicate the glitch. Let me know if you find a way to replicate it easily.

**Comment by dudedan7** [comment]
I was using the Beta 6 version, and any scrolling past a certain speed seemed to move it off it's snapping restraint slightly. Downloaded the Beta 6 Version 2 version and I cant seem to replicate it on this one, thanks for the fix! Attached video of the issue just in case it still holds any relevance: https://youtu.be/qMkoU8IIZV4
