### ISSUE TITLE
Feature Request: Extended options for time signatures

### ISSUE THREAD

**Issue by dudedan7** [Ikeiwa/EditSaber#7]
The majority of songs are still mappable even on a 4/4 grid so this isn't necessarily a pressing issue, however it would be a nice touch just so it looks cleaner on the grid and the larger beats fall on the larger white lines, etc.

**Comment by Ikeiwa** [comment]
So in the next release 1/3, 1/6... are possible. For the grid it would be hard for me to update its render.
