### ISSUE TITLE
Changing difficulties does not properly update difficulty.json file.

### ISSUE THREAD

**Issue by Renerrix** [Ikeiwa/EditSaber#8]
See [video](https://www.youtube.com/watch?v=GfQsfyv7U2k) for more information.

**Comment by Ikeiwa** [comment]
So it should be fixed in the next release, but don't forget to always do a backup when you edit a song.

**Comment by Renerrix** [comment]
This doesn't damage the file in any way, it simply doesn't properly update
the difficulty.
