### ISSUE TITLE
Changing place on the timeline does not update camera until song is played/resumed.

### ISSUE THREAD

**Issue by Renerrix** [Ikeiwa/EditSaber#9]
Results of this bug include being unable to properly edit the map, as anything placed at the currently location and camera placement will actually be placed at the current timeline position, even though the camera may not be looking at the timeline position.

Steps to reproduce:

- Place a light on the map.
- Click further along on the timeline.
- Place a light beside the light you already placed.

Expected result:

- Camera updates when timeline is changed.
OR
- Light is placed next to existing light.

Observed result:

- Camera does not update when timeline is updated;
- Light will be placed at the coordinates of the timeline as it is currently, whether you can see it or not. When resuming the song, the camera will snap to the timeline location and the light block you placed will be visible, nowhere near the original light.

**Comment by Ikeiwa** [comment]
I'm aware of this bug and is fixed in the current commit. The next release will not have this bug.
